<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.echocyan</groupId>
        <artifactId>code-nest-modules</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>code-nest-search</artifactId>
    <description>文章搜索</description>

    <dependencies>
        <dependency>
            <groupId>com.echocyan</groupId>
            <artifactId>code-nest-article</artifactId>
        </dependency>
        <dependency>
            <groupId>com.echocyan</groupId>
            <artifactId>code-nest-user</artifactId>
        </dependency>
    </dependencies>
</project>
