<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.echocyan</groupId>
        <artifactId>code-nest</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>code-nest-modules</artifactId>
    <packaging>pom</packaging>
    <description>业务模块的聚合与父 pom</description>

    <modules>
        <module>code-nest-article</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>com.echocyan</groupId>
            <artifactId>code-nest-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
